---
#-----
# Vars to set for all hosts:
# dhcp: yes or no
# int_name: the name of the interface to apply ip config to
# upload_type: default or smb
# boot_connect: yes or no
# ansible_user : username to use when connecting
# os_name: linux or windows
# operator_id: ID of the person on a machine
#---
# If localhost and not doing DHCP set the following vars:
# ip_address (CIDR Notation for Linux, normal for windows): X.X.X.X/XX or X.X.X.X
# win_netmask: X.X.X.X
# dns_servers: X.X.X.X (can be up to 2 of them in list format)
# gateway: X.X.X.X
#-----
all:
  vars:
    local_cache_dir: /var/cache/pyaccountabily
  children:
    team-example:
      vars:
        smb_mount: /mnt/myshare
        upload_user: bob-admin
        upload_dir: /sharedrive/artifacts
        upload_host: sharedrive.localnet.xyxa
      children:
        op-tomahawk:
          children:
            linux:
              vars:
                int_name: em1
                upload_type: default
                os_name: linux
                ansible_user: root
              children:
                scanner:
                  hosts:
                    127.0.0.1:
                      vars:
                        operator_id: Bob
            windows:
              vars:
                int_name: em1
                upload_type: default
                os_name: windows
                ansible_user: administrator
              hosts:
                somehost.windowshost:
                  vars:
                    operator_id: Bob
