---
# Standard Time Zone Format for location
timezone: Pacific Standard Time
# Optional packages to install (original 4 are needed for Ansible)
lin_packages:
  - nmcli
  - ntpdate
  - dbus
  - NetworkManager-glib
# Chocalety Packages to install
win_packages:



