---
- name: Setup Non-DHCP host
  nmcli:
    conn_name: "LAN_Network"
    type: ethernet
    ifname: "{{ int_name }}"
    state: present
    mtu: 1450
    ip4: "{{ ip_address }}"
    gw4: "{{ gateway }}"
    dns4: "{{ dns_servers }}"
  when: dhcp == "no"
  tags:
    - network

- name: Setup DHCP host
  nmcli:
    conn_name: "LAN_Network"
    type: ethernet
    ifname: "{{ int_name }}"
    state: present
    mtu: 1450
    ip4: "{{ ip_address }}"
    gw4: "{{ gateway }}"
    dns4: "{{ dns_servers }}"
  when: dhcp == "yes"
  tags:
    - network

- name: Setup autoconnect
  nmcli:
    conn_name: "LAN_Network"
    type: ethernet
    ifname: "*"
      autoconnect: "{{ boot_connect }}"
  tags:
    - network
