---
all:
  children:
    team1:
      vars:
        dhcp: yes
      children:
        blueteam:
          children:
            linux:
              vars:
                int_name: em1
                os_name: linux
              children:
                scanner:
                  hosts:
                    127.0.0.1

