---
- name: Create accountability directory
  win_file:
    path: "{{ windows_logdir }}"
    state: directory
    
- name: Create 64-bit PowerShell registry key
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell

- name: Create 64-bit PowerShell module logging registry key
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ModuleLogging

- name: Enable 64-bit PowerShell module logging
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ModuleLogging
    name: EnableModuleLogging
    data: 1
    type: dword
    
- name: Create 64-bit PowerShell module logging module names registry key
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ModuleLogging\ModuleNames
    
- name: Configure 64-bit PowerShell module logging for all modules
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ModuleLogging\ModuleNames
    name: *
    data: *

- name: Create 64-bit PowerShell script block logging registry key
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging

- name: Enable 64-bit PowerShell script block logging
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging
    name: EnableScriptBlockLogging
    data: 1
    type: dword
    
- name: Create 64-bit PowerShell transcription registry key
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription

- name: Enable 64-bit PowerShell transcription
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription
    name: EnableScriptBlockLogging
    data: 1
    type: dword
    
- name: Enable 64-bit PowerShell transcription envocation header
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription
    name: EnableInvocationHeader
    data: 1
    type: dword
    
- name: Configure 64-bit PowerShell transcription output directory
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription
    name: OutputDirectory
    data: "{{ windows_logdir }}"

- name: Create 32-bit PowerShell registry key
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell
    
- name: Create 32-bit PowerShell module logging registry key
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\ModuleLogging

- name: Enable 32-bit PowerShell module logging
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\ModuleLogging
    name: EnableModuleLogging
    data: 1
    type: dword
    
- name: Create 32-bit PowerShell module logging module names registry key
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\ModuleLogging\ModuleNames
    
- name: Configure 32-bit PowerShell module logging for all modules
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\ModuleLogging\ModuleNames
    name: *
    data: *

- name: Create 32-bit PowerShell script block logging registry key
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging

- name: Enable 32-bit PowerShell script block logging
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging
    name: EnableScriptBlockLogging
    data: 1
    type: dword
    
- name: Create 32-bit PowerShell transcription registry key
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\Transcription

- name: Enable 32-bit PowerShell transcription
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\Transcription
    name: EnableScriptBlockLogging
    data: 1
    type: dword
    
- name: Enable 32-bit PowerShell transcription envocation header
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\Transcription
    name: EnableInvocationHeader
    data: 1
    type: dword
    
- name: Configure 32-bit PowerShell transcription output directory
  win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\Transcription
    name: OutputDirectory
    data: "{{ windows_logdir }}"
