---
- name: Disable Firewall
  win_firewall:
    state: disabled
    profiles:
      - Domain
      - Private
      - Public
  tags:
    - firewall
- name: Set Firewall to Baseline
  win_command: "{{ items }}"
  loop:
    - netsh advfirewall firewall delete rule name=ALL
    - "netsh advfirewall firewall set allprofiles firewallpolicy {{ win_fw_policy }}"
  tags:
    - windows
    - firewall
- name: Allow Team In
  win_firewall_rule:
    name: Allow Team
    state: present
    direction: in
    remoteip: "{{ team_network}}"
    localport: "{{ windows_ports }}"
    enabled: yes
  tags:
    - firewall
- name: Allow outbound to team
  win_firewall_rule:
    name: Allow To Team
    state: present
    direction: out
    remoteip: "{{ team_network}}"
    enabled: yes
  tags:
    - firewall
- name: ALlow communications from trusted networks
  win_firewal_rule:
    name: Allow to trusted
    state: present
    direction: in
    remoteip: "{{ trusted_network }}"
  tags:
    - firewall
- name: Enable Firewall
  win_Firewall:
    state: enabled
    profiles:
      - Domain
      - Private
      - Public
  tags:
    - firewall