---
- name: do not store passwords using reversible encryption
  win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: 0
  tags:
    - system
- name: enable system events
  win_security_policy:
    section: Event Audit
    key: AuditSystemEvents
    value: 1
  tags:
    - system
- name: Set Timezone
  win_timezone:
    timezone: "{{ team_timezone }}"
  tags:
    - system
- name: set log retention
  win_eventlog:
    retention_days: 180
  tags:
    - system
- name: Set Host Name
  win_hostname:
    name: "{{ windows_hostname }}"
  register: res
  tags:
    - system
- name: Reboot system to apply name
  win_reboot:
  when: res.reboot_required
  tags:
    - system
