---
# Make sure interface is set to down
- name: Disable Interface
  command: "sudo ip link set down dev {{ int_name }}"
  tags:
    - system
    - linux
# Tell Linux to log any CLI commands entered
- name: Enabling CLI Logging
  lineinfile:
    regex: 'PROMPT_COMMAND='
    line: export PROMPT_COMMAND='history -a'
    path: /home/{{ username }}/.bashrc
  tags:
    - system
    - linux
# Install any packages needed
- name: Install Packages
  package:
    name: "{{ lin_packages }}"
    state: present
  tags:
    - system
    - linux
# Setup networking
- name: Setup IP address
  nmcli:
    conn_name: "LAN_Network"
    type: ethernet
    ifname: '*'
    state: present
    mtu: 1450
    dns4: "{{ dns_servers }}"
  tags:
    - system
    - linux
- name: Enable Interface
  command: "sudo ip link set up dev {{ int_name }}"
  tags:
    - system
    - linux
- name: Create Artifact Folder
  file:
    path: "{{ file_dir }}"
    state: directory
  tags:
    - system
    - linux
# TODO set ip address
# If method is smb, use smb for upload to shared location
- name: Mount SMB Share For Upload
  command: "{{ items }}"
  become: yes
  with_items:
    - "mount -t cifs -o username={{ upload_user }} //{{ upload_dir }}/{{ upload_share }} {{ file_dir }}"
  when: upload_type == "smb"
  register: smb_status
  tags:
    - system
    - linux
- debug: var=smb_status.stdout_lines





