---
- name: do not store passwords using reversible encryption
  win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: 0
  tags:
    - windows
    - system
- name: enable system events
  win_security_policy:
    section: Event Audit
    key: AuditSystemEvents
    value: 1
  tags:
    - windows
    - system
- name: Set Timezone
  win_timezone:
    timezone: "{{ team_timezone }}"
  tags:
    - windows
    - system
- name: set log retention
  win_eventlog:
    retention_days: 180
  tags:
    - windows
    - system
- name: Set Host Name
  win_hostname:
    name: "{{ windows_hostname }}"
  register: res
  tags:
    - windows
    - system
- name: Reboot system to apply name
  win_reboot:
  when: res.reboot_required
  tags:
    - windows
    - system
#-----
# DHCP Setup
#-----
- name: Start dhclient
  win_command: "{{ items }}"
  loop:
    - net start "DHCP Client"
    - netsh interface ipv4 set address name="Ethernet0" dhcp
  when: dhcp == "yes"
#-----
# Static setup
#-----
- name: Setting static IP address
  win_command: